name: Lighthouse
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: UnlyEd/github-action-await-vercel@v1.2.14
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: pkdx.wisesa.dev
          timeout: 30 # Wait for 30 seconds before failing
      - name: Deployment status
        run: "echo The deployment at ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }} is ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).readyState }}"
      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://pkdx.wisesa.dev/
            https://pkdx.wisesa.dev/about
            https://pkdx.wisesa.dev/my-pokemon
            https://pkdx.wisesa.dev/pokemon/rayquaza
          configPath: "./lighthouserc.json"
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3

