name: Test PkDx

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Install 🔧
        run: yarn

      - name: Test 🧪
        run: yarn test --coverage
